### PR TITLE
Add ownership validation

### PR DESCRIPTION
**Pull request by mbarnett**
To every object an owner, to every owner, many objects.

### CODE REVIEW

**Comment by mbarnett** [comment]
It's not clear to me what to do about all of these merge commits. I need to merge ualberta/jupiter/master into mbarnett/jupiter/master periodically, but as long as we keep squash merging back into ualberta/jupiter/master these just keep piling up.

And the alternatives seem problematic in other ways.

**Comment by murny** [comment]
For me since I work on a fork, I keep my work in branches on my fork and leave master untouched. Then when someone squashes commits into master (especially if its mine, since it changes git history), I pull down upstream master (ualbertalib/jupiter) like so `git pull upstream master` and then reset hard it into my master `git reset --hard upstream/master` (then sometimes i push this up to my origin) so that both masters are insync. Then I can merge master into my work branch with just one merge commit. If that makes sense

**Comment by mbarnett** [comment]
I'm concerned about committing things on my master, which happens occasionally even if it shouldn't, and then nuking it without realizing it with the hard rebase to upstream/master. I dunno, if other people feel that strongly about not seeing merge commits I can try it, I just don't personally care and think it'd be easier to just leave them intact and stop squashing altogether.

**Comment by mbarnett** [comment]
It's not clear to me that anything happy will happen if I branch off my master, pull master to my master later, hard rebase my master, and then try to rebase my branch, but I guess I'll cross that grenade when I get there.

**Comment by murny** [comment]
I personally dont care as we just going to squash these commits. So these 5+ merge master commits won't even be shown in master. So all good

**Comment by mbarnett** [comment]
Yeah, it's just that the next time I submit a PR, these 5 commits are going to show up again. And keep showing up, unless they make it into master or I rewrite my master's history

**Comment by cwant** [comment]
I just branch off of the ualbertalib master for all U of A work, way less fuss. I don't really see the advantage of forking into your own github account.

**Comment by mbarnett** [comment]
I don't know that it particularly has any, other than I feel less bad constantly force re-basing in-progress branches

**Pull request merged**
