### PR TITLE
Issue #119, remove redundant word from headers

### PR DESCRIPTION
**Pull request by cwant**
The labels "Community:", "Collection:" and "Item:" are removed from page headers (but not page titles).
Also did a bit of spacing/indenting tweaks on Collection/Community pages (e.g., community logo). Here are before/after screenshots showing tweaks:

community-tweak

collection-tweak

### CODE REVIEW

**Comment by murny** [comment]
Any reason not to change the page title (`<title></title>`) as well? They should be the same

**Comment by cwant** [comment]
I thought it was better keeping it in the title. Even if I changed it, the header and the title wouldn't be the same, since we append " | ERA" to our titles.

@sfbetz, @leahvanderjagt any opinion on this? Should the browser application title bars say:

"Community: The department of Unicorn | ERA"
"Collection: Theses about unicorns | ERA"
"Item: The effects of Nugget Nectar on unicorns | ERA"

or

"The department of Unicorn | ERA"
"Theses about unicorns | ERA"
"The effects of Nugget Nectar on unicorns | ERA"

(This is not the header on the page, but top of the browser window.)

**Comment by murny** [comment]
I am using my opinion from what others do in the wild. If you pick a website in the wild like...github/facebook/youtube/slideshare/linkedin/imdb/etc etc, 

Theres a really good chance you will always see the page title/header being the same in the fashon of `<resource_name> | <website_name>` and not `Resource: <resource_name> | <website_name>`.

**Comment by sfbetz** [comment]
Given limited real estate in places that display page titles (eg tabs), my preference is the latter - otherwise a user with many tabs (guilty) may see only the not-so-useful label Collection: or Item: in their browser, rather than more useful descriptive titles. Let's go with:

"The department of Unicorn | ERA"
"Theses about unicorns | ERA"
"The effects of Nugget Nectar on unicorns | ERA"

**Comment by cwant** [comment]
Shortened page titles.

**Pull request merged**
