### PR TITLE
Removed Matomo

### PR DESCRIPTION
**Pull request by ConnorSheremeta**
#1493

## Context
We no longer need Matomo tracking

### CODE REVIEW

**Comment by lagoan** [comment]
The travis build failed because you are trying to merge your PR from your fork. If you try to merge from a branch in the original repository the build should pass.

**Comment by ConnorSheremeta** [comment]
Right, forgot about that. Thanks Omar!

**Comment by murny** [comment]
Code looks good 👍

**Comment by ConnorSheremeta** [comment]
Closed in favour of https://github.com/ualbertalib/jupiter/pull/1601

**Pull request closed without merging**
