### PR TITLE
Loop additional solr indexes into solr_name_for

### LINKED ISSUE #276: Sort by `additional_search_index`
The indices defined by `additional_search_index` don't seem to be hooked up to sort in jupiter.

E.g., I expected this to work:

```ruby
# Define a search index
class Collection < JupiterCore::LockedLdpObject
  ...
  additional_search_index :community_title, solrize_for: :sort, as: -> { Community.find(community_id)&.title }
  ...
end

# Run a search
JupiterCore::Search.faceted_search(q: 'title_tesim:dogs', models: [Collection], as: user).sort(:community_title, :asc)
ArgumentError: No metadata found for attribute community_title
from /home/cwant/gitwork/jupiter/app/models/jupiter_core/deferred_faceted_solr_query.rb:45:in `sort'
```

### PR DESCRIPTION
**Pull request by mbarnett**
Closes #276

### CODE REVIEW

**Comment by cwant** [comment]
Still no dice. With the collection defined as in #276, I get:

```ruby
JupiterCore::Search.faceted_search(q: 'title_tesim:dogs', models: [Collection], as: user).sort(:community_title, :asc)

ArgumentError: No such attribute is defined, community_title
from /home/cwant/gitwork/jupiter/app/models/jupiter_core/locked_ldp_object.rb:205:in `solr_name_for'
```

**Comment by mbarnett** [comment]
JupiterCore::Search.faceted_search(q: 'title_tesim:dogs', models: [Collection]).sort(:community_title, :asc)
 => #<JupiterCore::DeferredFacetedSolrQuery:0x007fe1535e2748 @criteria={:q=>["(_query_:\"{!raw f=visibility_ssim}public\")", "title_tesim:dogs"], :qf=>"title_tesim description_tesim", :fq=>"", :facet_map=>{"visibility_ssim"=>:visibility, "visibility_sim"=>:visibility, "owner_ssim"=>:owner, "record_created_at_dtsi"=>:record_created_at, "title_tesim"=>:title, "title_ssi"=>:title, "community_id_dpsim"=>:community_id, "description_tesim"=>:description}, :facet_fields=>["visibility_sim", "community_id_dpsim"], :restrict_to_model=>[IRCollection], :facet_value_presenters=>{"community_id_dpsim"=>#<Proc:0x007fe14ebb38c0@/Users/matt/source/ualib/jupiter/app/models/collection.rb:13 (lambda)>}, :sort=>"community_title_ssim", :sort_order=>:asc}>

**Comment by mbarnett** [comment]
It looks like something is stale on your end? The error cites:

 /home/cwant/gitwork/jupiter/app/models/jupiter_core/locked_ldp_object.rb:205

but line 205 on this PR is in the middle of a comment block https://github.com/mbarnett/jupiter/blob/0b243145d41065ed86b2e2095e4a7f375a5208d6/app/models/jupiter_core/locked_ldp_object.rb#L205

**Comment by cwant** [comment]
Dagnabbit, I checked out the wrong branch from your remote (grabbed `solr_index_for` instead of `master`). It works as it does for you.

I do have an issue still though:

```ruby
JupiterCore::Search.faceted_search(q: 'title_tesim:dogs', models: [Collection], as: user).sort(:community_title, :asc).to_a        
                                                         
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":1,"params":{"q":"(_query_:\"{!raw f=has_model_ssim}IRCollection\") AND (_query_:\"{!raw f=visibility_ssim}public\" OR _query_:\"-visibility_ssim:[* TO *] AND *:*\" OR _query_:\"visibility_ssim:*\") AND title_tesim:dogs","facet.field":["visibility_sim","community_id_dpsim"],"qf":"title_tesim description_tesim","sort":"community_title_ssim asc","facet":"true","wt":"json"}},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"can not sort on multivalued field: community_title_ssim","code":400}}
```

It appears that this index is ill-defined for sorting -- do you have any recommendations?

**Comment by mbarnett** [comment]
That's a previously-undiscovered bug -- the solr indexes it produces aren't single valued. I'll fix it on this branch

**Comment by mbarnett** [comment]
Should be all fixed now

**Comment by cwant** [comment]
Yep, works:
```ruby
 JupiterCore::Search.faceted_search(q: 'title_tesim:*', models: [Collection], as: user).sort(:community_title, :asc).to_a.map { |collection| collection.community.title }
=> ["Special reports about dogs",
 "Special reports about dogs",
 "Special reports about hamburgers",
 "Special reports about hamburgers",
 "The department of Cat",
 "The department of Cat",
 "The department of Librarian",
 "The department of Librarian",
 "The department of Unicorn",
 "The department of Unicorn"]
```

**Comment by cwant** [comment]
Actually, I'm a bit surprised that 'The Everything Department' isn't in that list, since it is a community in the seeds with some collections. Don't know if that's related to this though, or something else (may need to poke around a bit still).

**Comment by mbarnett** [comment]
It's because of the default limit on search results. You just happen to not have any in your top 10 in that sort direction:

```ruby
2.4.1 :021 >  JupiterCore::Search.faceted_search(q: 'title_tesim:*', models: [Collection]).count
 => 10 
2.4.1 :022 > Collection.count
 => 22 
2.4.1 :023 >  JupiterCore::Search.faceted_search(q: 'title_tesim:*', models: [Collection]).sort(:community_title, :asc).map { |collection| collection.community.title }
 => ["Special reports about dogs", "Special reports about dogs", "Special reports about hamburgers", "Special reports about hamburgers", "The department of Cat", "The department of Cat", "The department of Librarian", "The department of Librarian", "The department of Unicorn", "The department of Unicorn"] 
2.4.1 :024 >  JupiterCore::Search.faceted_search(q: 'title_tesim:*', models: [Collection]).sort(:community_title, :desc).map { |collection| collection.community.title }
 => ["The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department", "The Everything Department"] 
```

(also that `to_a` call is unnecessary).

**Pull request merged**
