### PR TITLE
Cds/automate cl link verification

### PR DESCRIPTION
**Pull request by ConnorSheremeta**
https://github.com/ualbertalib/jupiter/issues/1966

Look through CL and see if there are any missing links in this release, give danger error if so.

### CODE REVIEW

**Comment by ConnorSheremeta** [comment]
> 1 Error
> 	
> The following CHANGELOG entries are missing a link to a PR/issue:
> 
> * Make reindex rake task actually reindex all of the objects into Solr, instead of acting as a no-op
>   – Fix a mis-named error rescue that resulted in a crash when the sort field wasn't known for a model
> 
> Generated by  [Danger](https://danger.systems/)

Looks to be working!

**Comment by ConnorSheremeta** [comment]
I'll probably end up squashing this? Lots of commits just for testing purposes.

**Comment by mbarnett** [comment]
Lol up to you. If you're just testing it wouldn't hurt to mark this PR as [WIP] though

**Comment by ConnorSheremeta** [comment]
Closed in favour of https://github.com/ualbertalib/jupiter/pull/2053

**Pull request closed without merging**
