### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by pbinkley**
MIT license is approved for DI work on Jupiter.

### CODE REVIEW

**Comment by cwant** [comment]
I would remove the "MIT License" line from the top of the file, as I think it affects how Github parses the file.  Compare for example the view of your license file, and an MIT Licence from another project:

https://github.com/ualbertalib/jupiter/blob/eafc5b839f3fb447ac3f89fd21fb2b21e4c7f5ff/LICENSE

https://github.com/mitmproxy/mitmproxy/blob/master/LICENSE

Github has added a summary of rights permissions/restrictions for the other file that isn't present in your file (and the only difference I can see is that first "MIT License" line).

**Comment by cwant** [comment]
Actually, it's quite possible the following is needed to add a license after the fact:

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by pbinkley** [comment]
I used the method Chris linked to, so that first line is part of the template Github provides. Maybe that summary only gets displayed when the license is in master? Github wants to display "how repositories on GitHub are licensed", so a license file in a non-master branch might not trigger their display. https://github.com/blog/2252-license-now-displayed-on-repository-overview . Why don't we merge and see how it looks, and fix it if it still doesn't show.

**Comment by cwant** [comment]
Yeah, merging into master did the trick.

**Pull request merged**
