### PR TITLE
[WIP] Inheritance fix -- Stop re-definining core functionality unless necessary

### LINKED ISSUE #352: Inheritance issues with JupiterCore::LockedLdpObject
I've pushed two branches related to thesis modelling, one that handles common behavior via concerns, the other that handles it via inheritance:

* Concerns:
  https://github.com/ualbertalib/jupiter/tree/cwant/issue_335_thesis_modeling_via_concerns
  Shared code module:  https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_concerns/app/models/concerns/base_item_behavior.rb
* Inheritance:
  https://github.com/ualbertalib/jupiter/tree/cwant/issue_335_thesis_modeling_via_inheritance
  Shared code ancestor: https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_inheritance/app/models/base_item.rb

The test suite runs fine for the first one (concerns), but a system test fails for the second one (inheritance). The test that fails in the inheritance branch isn't handling sorting by 'record_created_at' correctly, and this breakage also shows up in the console.

Although possibly unrelated, it's been confirmed that in the inheritance branch,  `JupiterCore::LockedLdpObject#set_record_created_at` gets run twice for instances of `Item`: https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_inheritance/app/models/jupiter_core/locked_ldp_object.rb#L490

### PR DESCRIPTION
**Pull request by mbarnett**
Fixes #352 (, at least on My Machine™)

### CODE REVIEW

**Comment by cwant** [comment]
When I cherry-pick my changes from the thesis modelling inheritance branch on top of your branch (`git cherry-pick d99f820db0c05a6abb5c99711c47f64df32037bd`) I still get the failing sorting test:

```
cwant@computy:~/gitwork/jupiter$ bin/rails test:system
Run options: --seed 18315

# Running:

Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.1-p111), codename: Love Song
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:44987
Use Ctrl-C to stop
..........[Screenshot]: tmp/screenshots/failures_test_: Searching as non-logged in user should be able to sort results. .png

F

Failure:
SearchTest#test_: Searching as non-logged in user should be able to sort results.  [/home/cwant/gitwork/jupiter/test/system/search_test.rb:247]:
Expected /Fancy Item 8.*Fancy Item 6.*Fancy Item 4.*Fancy Item 2.*Fancy Item 0/ to match "ERA Browse Deposit Search Log In This is a test message! Items (5) Collections (2) Communities (1) Filter Visibility Public 5 Collections Fancy Community 5 Fancy Community/Fancy Collection 0 3 Fancy Community/Fancy Collection 1 2 Languages English 5 Item type Article (Published) 5 Author / Creator / Contributor Joe Blow 5 Subject / Keyword Items 5 Results for \"Fancy\" Date (newest first) Thumbnail - Fancy Item 0 Fancy Item 0 Joe Blow Thumbnail - Fancy Item 2 Fancy Item 2 Joe Blow Thumbnail - Fancy Item 4 Fancy Item 4 Joe Blow Thumbnail - Fancy Item 6 Fancy Item 6 Joe Blow Thumbnail - Fancy Item 8 Fancy Item 8 Joe Blow 1 - 5 of 5".


bin/rails test test/system/search_test.rb:212

..........

Finished in 73.292079s, 0.2865 runs/s, 4.6935 assertions/s.
21 runs, 344 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by mbarnett** [comment]
I git popped this change into your branch and it was passing, but let me try cherry-picking that commit instead...

**Comment by mbarnett** [comment]
Nooow I've recreated it. Weird.

**Comment by mbarnett** [comment]
(Added WIP as this is hung up on other ActiveFedora bugs)

**Comment by mbarnett** [comment]
Backburnering this until I have more bandwidth.

**Pull request closed without merging**
