### PR TITLE
make department and supervisor a facet

### PR DESCRIPTION
**Pull request by pgwillia**
Requires reindex (I used `bundle exec rake jupiter:reindex` but perhaps there is a better way?)

Then the links to search can be treated the same as others.
Screenshot from 2019-03-29 12-48-07
Screenshot from 2019-03-29 12-44-24

### CODE REVIEW

**Comment by weiweishi** [comment]
I will run this with @abombak and @leahvanderjagt on this change.

**Comment by pgwillia** [comment]
I just double checked.  This will show a facet for each of department and supervisor if the search set includes results with these values
Screenshot from 2019-04-04 12-03-22

**Comment by weiweishi** [comment]
@pgwillia would you be able to deploy this on UAT when you have a moment, and send a note to Anna and Leah for their review? Sorry I dropped the ball on this one.

**Comment by pgwillia** [comment]
> @pgwillia would you be able to deploy this on UAT when you have a moment, and send a note to Anna and Leah for their review? Sorry I dropped the ball on this one.

Sent :)

**Comment by pgwillia** [comment]
There are concerns about the additional facets for department/supervisor appearing in the search results.  Closing for now, but maintaining the branch.

**Pull request closed without merging**
